spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: lixinxin
    password: LIxinxin**252511
    url: jdbc:mysql://39.107.225.207/db_weixin?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
          use-new-id-generator-mappings: false

server:
  servlet:
    context-path: /sell

#spring:
#  datasource:
#    primary:
#      url: jdbc:mysql://39.107.225.207/db_weixin?characterEncoding=utf-8&useSSL=false
#      username: root
#      password: LIxinxin**252511
#  jpa:
#    database: mysql
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy



#logging:
#  pattern:
 #   console: "%d - %msg%n"
#path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug
